import { StyleSheet } from "react-native";
import { COLORS, SPACING, RADIUS, FONTS, SHADOWS } from "../../constants";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },

  // SubView Header
  subViewHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray100,
    backgroundColor: COLORS.white,
    marginBottom: SPACING.lg,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.gray50,
    borderWidth: 1,
    borderColor: COLORS.gray100,
  },
  subViewHeaderTitle: {
    fontSize: FONTS.xl,
    fontWeight: "bold",
    color: COLORS.gray800,
  },

  // Content
  contentContainer: {
    flex: 1,
  },
  sectionContent: {
    flex: 1,
  },
  sectionScroll: {
    padding: SPACING.lg,
  },

  // Menú Principal Scroll
  menuScroll: {
    padding: SPACING.lg,
  },

  // Cabecera Integrada de Perfil (tarjeta profesional)
  profileHeaderCard: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: SPACING.lg,
    padding: SPACING.lg,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xl,
    ...SHADOWS.small,
    borderWidth: 1,
    borderColor: COLORS.gray100,
  },
  headerAvatarContainer: {
    marginRight: SPACING.lg,
  },
  headerAvatarRing: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 3,
    borderColor: COLORS.primary,
    padding: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarMain: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: COLORS.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarMainImage: {
    width: 60,
    height: 60,
    borderRadius: 30,
  },
  avatarTextMain: {
    fontSize: FONTS.xxl,
    fontWeight: "bold",
    color: COLORS.primary,
  },
  headerTextInfo: {
    flex: 1,
    justifyContent: "center",
  },
  profileMainName: {
    fontSize: FONTS.xl,
    fontWeight: "bold",
    color: COLORS.gray800,
    marginBottom: 2,
  },
  headerLocationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 6,
  },
  headerLocationText: {
    fontSize: FONTS.xs,
    color: COLORS.gray500,
    fontWeight: "500",
  },
  profileCompletionHint: {
    fontSize: FONTS.xs,
    color: COLORS.gray500,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  completionBarBackground: {
    height: 6,
    backgroundColor: COLORS.gray100,
    borderRadius: 3,
    marginTop: 6,
    overflow: "hidden",
  },
  completionBarFill: {
    height: "100%",
    backgroundColor: COLORS.primary,
    borderRadius: 3,
  },

  // Tarjeta Mi Bono Energético (en menú principal)
  bonoCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.warningSoft,
    borderRadius: RADIUS.lg,
    padding: SPACING.md,
    marginBottom: SPACING.lg,
    gap: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.warning,
  },
  bonoIconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.warning,
    alignItems: "center",
    justifyContent: "center",
  },
  bonoCardContent: {
    flex: 1,
  },
  bonoCardTitle: {
    fontSize: FONTS.md,
    fontWeight: "700",
    color: COLORS.warning,
    marginBottom: 2,
  },
  bonoCardSubtitle: {
    fontSize: FONTS.xs,
    color: COLORS.warning,
    fontWeight: "500",
  },

  // Bono Energético Section
  bonoProgressCard: {
    backgroundColor: COLORS.warningSoft,
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    marginBottom: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.warning,
  },
  bonoProgressHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    marginBottom: SPACING.md,
  },
  bonoProgressIconWrapper: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: COLORS.warning,
    alignItems: "center",
    justifyContent: "center",
  },
  bonoProgressInfo: {
    flex: 1,
  },
  bonoProgressTitle: {
    fontSize: FONTS.xxl,
    fontWeight: "bold",
    color: COLORS.warning,
    marginBottom: 2,
  },
  bonoProgressSubtitle: {
    fontSize: FONTS.sm,
    color: COLORS.warning,
    fontWeight: "500",
  },
  bonoProgressBarBg: {
    height: 8,
    backgroundColor: COLORS.white,
    borderRadius: 4,
    overflow: "hidden",
  },
  bonoProgressBarFill: {
    height: "100%",
    backgroundColor: COLORS.warning,
    borderRadius: 4,
  },
  bonoStepsCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xl,
    padding: SPACING.sm,
    marginBottom: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.warningSoft,
  },
  bonoStepsTitle: {
    fontSize: FONTS.md,
    fontWeight: "700",
    color: COLORS.warning,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.md,
  },
  bonoStepItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.warningSoft,
  },
  bonoStepLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    flex: 1,
  },
  bonoStepIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.warningSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  bonoStepContent: {
    flex: 1,
  },
  bonoStepHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 2,
  },
  bonoStepLabel: {
    fontSize: FONTS.md,
    fontWeight: "600",
    color: COLORS.gray800,
  },
  bonoStepBadge: {
    backgroundColor: COLORS.warning,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  bonoStepBadgeText: {
    fontSize: FONTS.xs,
    fontWeight: "700",
    color: COLORS.white,
  },
  bonoStepMessage: {
    fontSize: FONTS.xs,
    color: COLORS.warning,
    fontWeight: "500",
  },
  bonoCompleteCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xl,
    padding: SPACING.xl,
    alignItems: "center",
    marginBottom: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.gray100,
  },
  bonoCompleteTitle: {
    fontSize: FONTS.xxl,
    fontWeight: "bold",
    color: COLORS.gray800,
    marginTop: SPACING.md,
    marginBottom: SPACING.xs,
  },
  bonoCompleteSubtitle: {
    fontSize: FONTS.sm,
    color: COLORS.gray500,
    textAlign: "center",
  },

  // Panel de ayuda CAE
  caeHelpCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xl,
    padding: SPACING.md,
    marginBottom: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.gray100,
  },
  caeHelpHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  caeHelpHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  caeHelpTitle: {
    fontSize: FONTS.md,
    fontWeight: "700",
    color: COLORS.gray800,
  },
  caeHelpContent: {
    marginTop: SPACING.md,
    gap: SPACING.md,
  },
  caeHelpSectionTitle: {
    fontSize: FONTS.sm,
    fontWeight: "700",
    color: COLORS.warning,
    marginBottom: SPACING.xs,
  },
  caeHelpText: {
    fontSize: FONTS.sm,
    color: COLORS.gray600,
    lineHeight: 20,
  },
  caeHelpStepRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.sm,
    marginBottom: SPACING.xs,
  },
  caeHelpStepBadge: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: COLORS.warning,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  caeHelpStepBadgeText: {
    fontSize: FONTS.xs,
    fontWeight: "700",
    color: COLORS.white,
  },

  // Tarjeta verde de Ahorro generado
  savingsCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    marginBottom: SPACING.lg,
    ...SHADOWS.small,
  },
  savingsLeft: {
    flex: 1,
  },
  savingsIconLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  savingsLabel: {
    fontSize: FONTS.sm,
    fontWeight: "700",
    color: COLORS.white,
    opacity: 0.9,
  },
  infoCircle: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.5)",
    alignItems: "center",
    justifyContent: "center",
  },
  infoCircleText: {
    fontSize: 9,
    fontWeight: "bold",
    color: COLORS.white,
  },
  savingsDate: {
    fontSize: FONTS.xs,
    color: "rgba(255,255,255,0.7)",
    fontWeight: "500",
  },
  savingsValue: {
    fontSize: 28,
    fontWeight: "bold",
    color: COLORS.white,
  },

  // Estadísticas en 3 Columnas
  statsCardBlock: {
    flexDirection: "row",
    alignItems: "stretch",
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xl,
    paddingVertical: SPACING.lg,
    marginBottom: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    ...SHADOWS.small,
  },
  statsCol: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  statsDividerLine: {
    width: 1,
    backgroundColor: COLORS.gray100,
    marginVertical: 4,
  },
  statsValueNumber: {
    fontSize: FONTS.xl,
    fontWeight: "bold",
    color: COLORS.primary,
    marginBottom: 2,
  },
  statsColLabel: {
    fontSize: 11,
    color: COLORS.gray500,
    textAlign: "center",
    lineHeight: 14,
    fontWeight: "500",
  },

  // Menú de opciones de lista vertical
  menuItemsBlock: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xl,
    paddingHorizontal: SPACING.md,
    marginBottom: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    ...SHADOWS.small,
  },
  menuRowItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.xs,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray50,
  },
  menuRowLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    flex: 1,
  },
  menuRowIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  menuRowText: {
    fontSize: FONTS.md,
    fontWeight: "500",
    color: COLORS.gray800,
    flex: 1,
  },
  menuSectionDivider: {
    height: 1,
    backgroundColor: COLORS.gray100,
    marginHorizontal: -SPACING.md,
    marginVertical: SPACING.xs,
  },
  menuSectionLabel: {
    fontSize: FONTS.xs,
    fontWeight: "700",
    color: COLORS.gray400,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    paddingHorizontal: SPACING.xs,
    paddingTop: SPACING.md,
    paddingBottom: SPACING.xs,
  },

  // Botón de Cerrar Sesión del Menú
  menuLogoutButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: SPACING.sm,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xl,
    paddingVertical: SPACING.md,
    marginTop: SPACING.sm,
    marginBottom: SPACING.xl,
    borderWidth: 1,
    borderColor: COLORS.errorSoft,
    ...SHADOWS.small,
  },
  menuLogoutText: {
    fontSize: FONTS.md,
    color: COLORS.error,
    fontWeight: "700",
  },

  // Edit form / Datos personales
  editAvatarSection: {
    alignItems: "center",
    marginBottom: SPACING.lg,
    marginTop: SPACING.sm,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xl,
    paddingVertical: SPACING.xl,
    paddingHorizontal: SPACING.lg,
    ...SHADOWS.small,
    borderWidth: 1,
    borderColor: COLORS.gray100,
  },
  editAvatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: COLORS.primarySoft,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: SPACING.xs,
  },
  editAvatarText: {
    fontSize: FONTS.xxxl,
    fontWeight: "bold",
    color: COLORS.primary,
  },
  editAvatarName: {
    fontSize: FONTS.xl,
    fontWeight: "bold",
    color: COLORS.gray800,
    marginTop: SPACING.xs,
  },
  editAvatarLocation: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 4,
  },
  editAvatarLocationText: {
    fontSize: FONTS.sm,
    color: COLORS.gray500,
    fontWeight: "500",
  },
  editAvatarWithCamera: {
    position: "relative",
    marginBottom: SPACING.xs,
  },
  editAvatarImage: {
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 3,
    borderColor: COLORS.primary,
  },
  editAvatarCameraBtn: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: COLORS.white,
    ...SHADOWS.small,
  },
  editAvatarSubHint: {
    fontSize: FONTS.xs,
    color: COLORS.gray400,
    marginTop: SPACING.xs,
  },

  // Banner de completitud del perfil
  completionBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.primarySoft,
    borderRadius: RADIUS.lg,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    marginBottom: SPACING.lg,
  },
  completionBannerLeft: {
    flex: 1,
  },
  completionBannerTitle: {
    fontSize: FONTS.sm,
    fontWeight: "700",
    color: COLORS.primary,
  },
  completionBannerSubtitle: {
    fontSize: FONTS.xs,
    color: COLORS.gray600,
    marginTop: 2,
  },
  completionBannerRight: {
    alignItems: "flex-end",
    width: 100,
  },
  completionBannerPercent: {
    fontSize: FONTS.lg,
    fontWeight: "bold",
    color: COLORS.primary,
    marginBottom: 4,
  },
  editFormCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: SPACING.lg,
    ...SHADOWS.small,
    marginBottom: SPACING.xl,
  },
  editField: {
    marginBottom: SPACING.lg,
    position: "relative",
  },
  editFieldLabel: {
    fontSize: FONTS.sm,
    fontWeight: "600",
    color: COLORS.gray700,
    marginBottom: SPACING.sm,
  },
  editInputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.lg,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    backgroundColor: COLORS.white,
  },
  editInput: {
    flex: 1,
    fontSize: FONTS.md,
    color: COLORS.gray800,
    paddingVertical: 0,
  },
  saveProfileBtn: {
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.lg,
    paddingVertical: SPACING.md,
    alignItems: "center",
    justifyContent: "center",
  },
  editButtonRow: {
    flexDirection: "row",
    gap: SPACING.md,
    width: "100%",
  },
  saveProfileBtnText: {
    fontSize: FONTS.md,
    fontWeight: "700",
    color: COLORS.white,
  },

  // Nuevos estilos para secciones de Mi Perfil
  sectionCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    marginBottom: SPACING.lg,
    ...SHADOWS.small,
    borderWidth: 1,
    borderColor: COLORS.gray100,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    marginBottom: SPACING.md,
    paddingBottom: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray100,
  },
  sectionIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  sectionTitle: {
    fontSize: FONTS.lg,
    fontWeight: "bold",
    color: COLORS.gray800,
    flex: 1,
  },
  editHeaderBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.secondarySoft,
  },
  sectionEditBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.secondarySoft,
  },
  sectionEditBtnText: {
    fontSize: FONTS.sm,
    fontWeight: "600",
    color: COLORS.secondary,
  },
  viewField: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    paddingVertical: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray50,
  },
  viewFieldIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.gray50,
    alignItems: "center",
    justifyContent: "center",
  },
  viewFieldContent: {
    flex: 1,
  },
  viewFieldLabel: {
    fontSize: FONTS.xs,
    fontWeight: "700",
    color: COLORS.gray400,
    marginBottom: 2,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  viewFieldValue: {
    fontSize: FONTS.md,
    color: COLORS.gray800,
    fontWeight: "500",
  },
  viewAboutMe: {
    fontSize: FONTS.md,
    color: COLORS.gray700,
    lineHeight: 24,
  },
  viewAboutMeContainer: {
    paddingVertical: SPACING.sm,
  },
  viewAboutMeEmpty: {
    alignItems: "center",
    gap: SPACING.sm,
    paddingVertical: SPACING.lg,
    backgroundColor: COLORS.gray50,
    borderRadius: RADIUS.lg,
    paddingHorizontal: SPACING.md,
  },
  viewAboutMeEmptyText: {
    fontSize: FONTS.sm,
    color: COLORS.gray400,
    textAlign: "center",
  },
  datePickerButton: {
    width: "100%",
  },
  editInputPlaceholder: {
    color: COLORS.gray400,
  },
  genderPicker: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.md,
  },
  genderOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    backgroundColor: COLORS.gray50,
    borderWidth: 1,
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.full,
  },
  genderOptionSelected: {
    backgroundColor: COLORS.primarySoft,
    borderColor: COLORS.primary,
  },
  genderRadio: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: COLORS.gray300,
  },
  genderRadioSelected: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primary,
  },
  genderOptionText: {
    fontSize: FONTS.md,
    color: COLORS.gray700,
    fontWeight: "500",
  },
  genderOptionTextSelected: {
    color: COLORS.primary,
    fontWeight: "600",
  },

  // Valoraciones
  ratingsCard: {
    padding: 0,
  },
  ratingSummary: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.warning + "08",
    borderRadius: RADIUS.lg,
    padding: SPACING.lg,
    marginBottom: SPACING.md,
  },
  ratingMain: {
    flex: 1,
    alignItems: "flex-start",
  },
  ratingValue: {
    fontSize: 40,
    fontWeight: "bold",
    color: COLORS.warning,
    lineHeight: 48,
  },
  ratingStars: {
    flexDirection: "row",
    marginTop: SPACING.xs,
    marginBottom: SPACING.xs,
  },
  ratingCount: {
    fontSize: FONTS.sm,
    color: COLORS.gray500,
    fontWeight: "500",
  },
  ratingAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: COLORS.gray100,
  },
  ratingActionText: {
    fontSize: FONTS.sm,
    fontWeight: "600",
    color: COLORS.gray700,
  },
  ratingDivider: {
    height: 1,
    backgroundColor: COLORS.gray100,
    marginVertical: SPACING.sm,
  },
  ratingInfo: {
    gap: SPACING.xs,
  },
  ratingInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    paddingVertical: SPACING.sm,
  },
  ratingInfoIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  ratingInfoText: {
    flex: 1,
    fontSize: FONTS.md,
    color: COLORS.gray700,
    fontWeight: "500",
  },

  // Sobre mí
  aboutMeInput: {
    minHeight: 100,
    paddingTop: SPACING.md,
    paddingBottom: SPACING.md,
  },
  aboutMeHint: {
    fontSize: FONTS.xs,
    color: COLORS.gray400,
    textAlign: "right",
    marginTop: SPACING.xs,
  },

  // Estilos de Viajes Section (Historial de trayectos)
  centerContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: SPACING.xl,
  },
  loadingText: {
    fontSize: FONTS.md,
    color: COLORS.gray600,
    marginTop: SPACING.md,
    fontWeight: "500",
  },
  errorText: {
    fontSize: FONTS.md,
    color: COLORS.error,
    textAlign: "center",
    marginBottom: SPACING.md,
  },
  retryButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.lg,
    borderRadius: RADIUS.md,
  },
  retryButtonText: {
    color: COLORS.white,
    fontWeight: "600",
    fontSize: FONTS.sm,
  },
  viajesScrollContent: {
    paddingBottom: SPACING.xxl,
  },
  fechaGrupoContainer: {
    marginBottom: SPACING.xl,
    paddingHorizontal: SPACING.lg,
  },
  fechaGrupoTitulo: {
    fontSize: FONTS.md,
    fontWeight: "bold",
    color: COLORS.gray700,
    marginBottom: SPACING.md,
    marginLeft: SPACING.xs,
  },
  viajeCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    marginBottom: SPACING.md,
    ...SHADOWS.medium,
  },
  viajeCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: SPACING.md,
  },
  badgeWrapper: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
  },
  rolBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
  },
  conductorBadge: {
    backgroundColor: COLORS.primarySoft,
  },
  pasajeroBadge: {
    backgroundColor: COLORS.secondarySoft,
  },
  rolBadgeText: {
    fontSize: FONTS.xs,
    fontWeight: "700",
  },
  conductorBadgeText: {
    color: COLORS.primary,
  },
  pasajeroBadgeText: {
    color: COLORS.secondary,
  },
  statusBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
  },
  pendingStatusBadge: {
    backgroundColor: COLORS.warningSoft,
  },
  activeStatusBadge: {
    backgroundColor: COLORS.successSoft,
  },
  successStatusBadge: {
    backgroundColor: COLORS.gray100,
  },
  statusBadgeText: {
    fontSize: FONTS.xs,
    fontWeight: "600",
  },
  pendingStatusBadgeText: {
    color: COLORS.warning,
  },
  activeStatusBadgeText: {
    color: COLORS.success,
  },
  successStatusBadgeText: {
    color: COLORS.gray600,
  },
  viajePrice: {
    fontSize: FONTS.lg,
    fontWeight: "bold",
    color: COLORS.gray900,
  },
  viajeCardRoute: {
    flexDirection: "row",
    gap: SPACING.md,
    marginBottom: SPACING.md,
    paddingHorizontal: SPACING.xs,
  },
  routeTimeline: {
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 4,
  },
  timelineDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  timelineLine: {
    flex: 1,
    width: 2,
    backgroundColor: COLORS.gray200,
    marginVertical: 4,
  },
  routePlaces: {
    flex: 1,
    gap: SPACING.lg,
  },
  routePlaceText: {
    fontSize: FONTS.sm,
    color: COLORS.gray800,
    fontWeight: "500",
  },
  viajeCardFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: COLORS.gray100,
    paddingTop: SPACING.md,
  },
  footerInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.lg,
  },
  footerInfoItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  footerInfoText: {
    fontSize: FONTS.xs,
    color: COLORS.gray500,
    fontWeight: "500",
  },

  // Estilos de Coches (Vehículos)
  bottomFixedBtnContainer: {
    paddingHorizontal: SPACING.xl,
    paddingTop: SPACING.sm,
    paddingBottom: SPACING.lg,
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: COLORS.gray100,
  },
  addCocheMainBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: SPACING.sm,
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.lg,
    paddingVertical: SPACING.md,
    ...SHADOWS.small,
  },
  addCocheMainBtnText: {
    color: COLORS.white,
    fontSize: FONTS.md,
    fontWeight: "700",
  },
  cochesListContainer: {
    gap: SPACING.lg,
  },
  cocheItemCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    ...SHADOWS.small,
    borderWidth: 1,
    borderColor: COLORS.gray100,
  },
  cocheCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: SPACING.md,
  },
  cocheCardInfoMain: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
  },
  cocheCardIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  cocheCardBrandModel: {
    fontSize: FONTS.lg,
    fontWeight: "700",
    color: COLORS.gray800,
  },
  cocheCardColorYear: {
    fontSize: FONTS.xs,
    color: COLORS.gray400,
    fontWeight: "500",
    marginTop: 2,
  },
  cocheCardActions: {
    flexDirection: "row",
    gap: SPACING.sm,
  },
  cocheActionBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.gray50,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: COLORS.gray100,
  },
  cocheActionBtnDelete: {
    backgroundColor: "#FEE2E2",
    borderColor: "#FCA5A5",
  },
  cocheSpecsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    marginTop: SPACING.md,
    borderTopWidth: 1,
    borderTopColor: COLORS.gray100,
    paddingTop: SPACING.md,
  },
  cocheSpecBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: COLORS.gray50,
    paddingHorizontal: SPACING.md,
    paddingVertical: 6,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLORS.gray100,
  },
  cocheSpecText: {
    fontSize: 12,
    color: COLORS.gray600,
    fontWeight: "500",
  },
  combustibleIndicatorDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },

  // Placa de Matrícula Realista
  matriculaPlacaOuter: {
    alignItems: "center",
    marginVertical: SPACING.xs,
  },
  matriculaPlacaInner: {
    flexDirection: "row",
    alignItems: "stretch",
    backgroundColor: COLORS.white,
    borderWidth: 2,
    borderColor: "#333333",
    borderRadius: 4,
    height: 44,
    width: "100%",
    maxWidth: 240,
    overflow: "hidden",
  },
  placaBandaUE: {
    backgroundColor: "#003399",
    width: 28,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 2,
  },
  placaStars: {
    color: "#FFCC00",
    fontSize: 8,
    lineHeight: 8,
    textAlign: "center",
  },
  placaPais: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: "bold",
    marginTop: 2,
  },
  placaDigitosContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.white,
  },
  placaDigitosText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#111111",
    letterSpacing: 2,
  },

  // Chips para Formulario de Coches
  chipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
    marginTop: SPACING.xs,
  },
  chipBtn: {
    backgroundColor: COLORS.gray50,
    borderWidth: 1,
    borderColor: COLORS.gray200,
    paddingHorizontal: SPACING.md,
    paddingVertical: 8,
    borderRadius: RADIUS.lg,
  },
  chipBtnSelected: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  chipBtnText: {
    fontSize: 12,
    color: COLORS.gray600,
    fontWeight: "600",
  },
  chipBtnTextSelected: {
    color: COLORS.white,
  },
  colorChipBtn: {
    backgroundColor: COLORS.gray50,
    borderWidth: 1,
    borderColor: COLORS.gray200,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 6,
    borderRadius: RADIUS.md,
  },
  colorChipBtnSelected: {
    backgroundColor: COLORS.gray800,
    borderColor: COLORS.gray800,
  },
  colorChipText: {
    fontSize: 11,
    color: COLORS.gray600,
    fontWeight: "500",
  },
  colorChipTextSelected: {
    color: COLORS.white,
  },

  // Autocompletado de Marcas y Modelos
  suggestionsContainer: {
    position: "absolute",
    top: 72,
    left: 0,
    right: 0,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.md,
    maxHeight: 180,
    overflow: "scroll",
    ...SHADOWS.medium,
    zIndex: 9999,
  },
  suggestionItem: {
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray100,
  },
  suggestionText: {
    fontSize: FONTS.md,
    color: COLORS.gray700,
  },

  placeholderContainer: {
    alignItems: "center",
    justifyContent: "center",
    padding: SPACING.xl,
    marginTop: SPACING.xxl,
  },
  placeholderIconBg: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: COLORS.gray100,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: SPACING.lg,
  },
  placeholderTitle: {
    fontSize: FONTS.xl,
    fontWeight: "bold",
    color: COLORS.gray700,
    marginBottom: SPACING.sm,
  },
  placeholderSubtitle: {
    fontSize: FONTS.md,
    color: COLORS.gray400,
    textAlign: "center",
    maxWidth: 280,
  },

  // ===== Monedero / Wallet =====
  walletLoadingContainer: {
    alignItems: "center",
    paddingVertical: SPACING.xxl,
    gap: SPACING.sm,
  },
  walletLoadingText: {
    fontSize: FONTS.sm,
    color: COLORS.gray500,
  },
  walletErrorContainer: {
    alignItems: "center",
    paddingVertical: SPACING.xl,
    gap: SPACING.md,
  },
  walletDisponibleCard: {
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.xl,
    padding: SPACING.xl,
    marginBottom: SPACING.md,
    ...SHADOWS.md,
  },
  walletDisponibleHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  walletDisponibleIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  walletDisponibleLabel: {
    fontSize: FONTS.lg,
    fontWeight: "700",
    color: COLORS.white,
  },
  walletDisponibleSublabel: {
    fontSize: FONTS.xs,
    color: "rgba(255,255,255,0.7)",
    marginTop: 2,
  },
  walletDisponibleAmount: {
    fontSize: 40,
    fontWeight: "bold",
    color: COLORS.white,
    marginBottom: SPACING.md,
  },
  walletDisponibleBreakdown: {
    gap: SPACING.xs,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: RADIUS.lg,
    padding: SPACING.md,
  },
  walletDisponibleBreakdownItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingVertical: 4,
  },
  walletDisponibleBreakdownLabel: {
    flex: 1,
    fontSize: FONTS.sm,
    color: "rgba(255,255,255,0.8)",
    fontWeight: "500",
  },
  walletDisponibleBreakdownValue: {
    fontSize: FONTS.sm,
    color: COLORS.white,
    fontWeight: "700",
  },
  walletRevisionCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xl,
    padding: SPACING.xl,
    marginBottom: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.warning + "30",
    ...SHADOWS.sm,
  },
  walletRevisionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  walletRevisionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.warningSoft || "rgba(245,158,11,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  walletRevisionLabel: {
    fontSize: FONTS.lg,
    fontWeight: "700",
    color: COLORS.gray800,
  },
  walletRevisionSublabel: {
    fontSize: FONTS.xs,
    color: COLORS.gray500,
    marginTop: 2,
  },
  walletRevisionAmount: {
    fontSize: 32,
    fontWeight: "bold",
    color: COLORS.warning,
    marginBottom: SPACING.md,
  },
  walletRevisionBreakdown: {
    gap: SPACING.xs,
    backgroundColor: COLORS.gray50,
    borderRadius: RADIUS.lg,
    padding: SPACING.md,
  },
  walletRevisionBreakdownItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingVertical: 4,
  },
  walletRevisionBreakdownLabel: {
    flex: 1,
    fontSize: FONTS.sm,
    color: COLORS.gray600,
    fontWeight: "500",
  },
  walletRevisionBreakdownValue: {
    fontSize: FONTS.sm,
    color: COLORS.gray900,
    fontWeight: "700",
  },
  walletRevisionEmpty: {
    fontSize: FONTS.sm,
    color: COLORS.gray400,
    textAlign: "center",
    paddingVertical: SPACING.xs,
  },
  walletBreakdownDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  walletBalanceCard: {
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.xl,
    padding: SPACING.xl,
    marginBottom: SPACING.lg,
    ...SHADOWS.md,
  },
  walletBalanceHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  walletIconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  walletBalanceLabel: {
    fontSize: FONTS.md,
    fontWeight: "600",
    color: COLORS.white,
  },
  walletBalanceAmount: {
    fontSize: 36,
    fontWeight: "bold",
    color: COLORS.white,
    marginBottom: 4,
  },
  walletBalanceHint: {
    fontSize: FONTS.xs,
    color: "rgba(255,255,255,0.7)",
  },
  // ===== CAE (Certificados de Ahorro de Energía) =====
  caeCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    marginBottom: SPACING.lg,
    ...SHADOWS.md,
  },
  caeHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  caeIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  caeTitle: {
    fontSize: FONTS.sm,
    fontWeight: "700",
    color: COLORS.gray800,
  },
  caeSubtitle: {
    fontSize: FONTS.xs,
    color: COLORS.gray500,
    marginTop: 2,
  },
  caeMainAmount: {
    backgroundColor: COLORS.gray50,
    borderRadius: RADIUS.lg,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    alignItems: "center",
    marginBottom: SPACING.md,
  },
  caeMainLabel: {
    fontSize: FONTS.xs,
    color: COLORS.gray500,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  caeMainValue: {
    fontSize: 28,
    fontWeight: "bold",
    color: COLORS.gray900,
    marginTop: 4,
  },
  caeBreakdown: {
    gap: SPACING.sm,
  },
  caeBreakdownItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingVertical: SPACING.xs,
  },
  caeBreakdownDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  caeBreakdownLabel: {
    fontSize: FONTS.sm,
    color: COLORS.gray600,
    fontWeight: "500",
  },
  caeBreakdownValue: {
    fontSize: FONTS.sm,
    color: COLORS.gray900,
    fontWeight: "700",
    marginTop: 2,
  },
  caeDetailsSection: {
    marginTop: SPACING.md,
    paddingTop: SPACING.md,
    borderTopWidth: 1,
    borderTopColor: COLORS.gray100,
  },
  caeDetailsTitle: {
    fontSize: FONTS.xs,
    fontWeight: "700",
    color: COLORS.gray600,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: SPACING.sm,
  },
  caeDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingVertical: SPACING.xs,
  },
  caeDetailIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORS.gray50,
    alignItems: "center",
    justifyContent: "center",
  },
  caeDetailKm: {
    fontSize: FONTS.sm,
    fontWeight: "600",
    color: COLORS.gray800,
  },
  caeDetailDate: {
    fontSize: FONTS.xs,
    color: COLORS.gray400,
    marginTop: 2,
  },
  caeDetailEur: {
    fontSize: FONTS.sm,
    fontWeight: "700",
    color: COLORS.success,
  },
  caeDetailStatus: {
    fontSize: FONTS.xs,
    fontWeight: "500",
    marginTop: 2,
    color: COLORS.gray500,
  },
  walletActionsRow: {
    flexDirection: "row",
    gap: SPACING.sm,
    marginBottom: SPACING.lg,
  },
  walletActionBtn: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    paddingVertical: SPACING.md,
    alignItems: "center",
    ...SHADOWS.sm,
  },
  walletActionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.secondarySoft,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: SPACING.xs,
  },
  walletActionText: {
    fontSize: FONTS.xs,
    fontWeight: "600",
    color: COLORS.gray700,
    textAlign: "center",
  },
  stripeConnectedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    backgroundColor: COLORS.success + "15",
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    marginBottom: SPACING.lg,
  },
  stripeConnectedText: {
    fontSize: FONTS.sm,
    color: COLORS.success,
    fontWeight: "600",
  },
  stripeConnectCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: SPACING.md,
    marginBottom: SPACING.lg,
    ...SHADOWS.sm,
  },
  stripeConnectLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    flex: 1,
  },
  stripeConnectIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  stripeConnectTitle: {
    fontSize: FONTS.sm,
    fontWeight: "700",
    color: COLORS.gray800,
  },
  stripeConnectSubtitle: {
    fontSize: FONTS.xs,
    color: COLORS.gray500,
    marginTop: 2,
  },
  walletSectionCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: SPACING.md,
    marginBottom: SPACING.lg,
    ...SHADOWS.sm,
  },
  walletSectionTitle: {
    fontSize: FONTS.md,
    fontWeight: "700",
    color: COLORS.gray800,
    marginBottom: SPACING.sm,
  },
  walletErrorText: {
    fontSize: FONTS.sm,
    color: COLORS.error,
    marginBottom: SPACING.sm,
  },
  walletRetryBtn: {
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.xs,
    backgroundColor: COLORS.primarySoft,
    borderRadius: RADIUS.full,
  },
  walletRetryBtnText: {
    fontSize: FONTS.sm,
    fontWeight: "600",
    color: COLORS.primary,
  },
  walletEmptyText: {
    fontSize: FONTS.sm,
    color: COLORS.gray400,
    paddingVertical: SPACING.md,
    textAlign: "center",
  },
  walletTxRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray50,
  },
  walletTxIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.gray50,
    alignItems: "center",
    justifyContent: "center",
  },
  walletTxDesc: {
    fontSize: FONTS.sm,
    fontWeight: "600",
    color: COLORS.gray800,
  },
  walletTxDate: {
    fontSize: FONTS.xs,
    color: COLORS.gray400,
    marginTop: 2,
  },
  walletTxAmount: {
    fontSize: FONTS.sm,
    fontWeight: "700",
    color: COLORS.gray800,
  },
  walletPayoutStatus: {
    fontSize: FONTS.xs,
    fontWeight: "500",
    marginTop: 2,
  },
  payoutModalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
  },
  payoutModalCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xl,
    padding: SPACING.xl,
    width: "85%",
    ...SHADOWS.lg,
  },
  payoutModalTitle: {
    fontSize: FONTS.lg,
    fontWeight: "bold",
    color: COLORS.gray800,
    marginBottom: SPACING.xs,
  },
  payoutModalSubtitle: {
    fontSize: FONTS.sm,
    color: COLORS.gray500,
    marginBottom: SPACING.lg,
  },
  payoutInputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.md,
    marginBottom: SPACING.lg,
  },
  payoutInput: {
    flex: 1,
    fontSize: FONTS.xl,
    fontWeight: "600",
    color: COLORS.gray800,
    paddingVertical: SPACING.md,
  },
  payoutInputSuffix: {
    fontSize: FONTS.xl,
    fontWeight: "600",
    color: COLORS.gray400,
  },
  payoutModalActions: {
    flexDirection: "row",
    gap: SPACING.sm,
  },
  payoutModalBtn: {
    flex: 1,
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.md,
    alignItems: "center",
    justifyContent: "center",
  },
  payoutModalBtnText: {
    fontSize: FONTS.sm,
    fontWeight: "700",
    color: COLORS.white,
  },

  // ===== Cuentas vinculadas (tarjetas y bancos) =====
  linkedAccountsTitle: {
    fontSize: FONTS.lg,
    fontWeight: "700",
    color: COLORS.gray800,
    marginBottom: SPACING.md,
  },
  linkedAccountsList: {
    gap: SPACING.md,
    marginBottom: SPACING.lg,
  },
  bankCard: {
    borderRadius: 16,
    padding: SPACING.lg,
    minHeight: 180,
    justifyContent: "space-between",
    ...SHADOWS.md,
    overflow: "hidden",
  },
  bankCardVisa: {
    backgroundColor: "#1A1F71",
  },
  bankCardMastercard: {
    backgroundColor: "#EB001B",
  },
  bankCardAmex: {
    backgroundColor: "#006FCF",
  },
  bankCardTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  bankCardChip: {
    width: 40,
    height: 30,
    borderRadius: 6,
    backgroundColor: "rgba(255,255,255,0.25)",
  },
  bankCardBrand: {
    fontSize: FONTS.md,
    fontWeight: "800",
    color: COLORS.white,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  bankCardNumber: {
    fontSize: FONTS.lg,
    fontWeight: "700",
    color: COLORS.white,
    letterSpacing: 2,
    marginBottom: SPACING.md,
  },
  bankCardBottom: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  bankCardLabel: {
    fontSize: FONTS.xs,
    color: "rgba(255,255,255,0.6)",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  bankCardValue: {
    fontSize: FONTS.sm,
    fontWeight: "600",
    color: COLORS.white,
    marginTop: 2,
  },
  bankCardBrandCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  bankCardBrandCircleText: {
    fontSize: FONTS.md,
    fontWeight: "800",
    color: COLORS.white,
  },
  bankAccountCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: SPACING.md,
    ...SHADOWS.sm,
  },
  bankAccountLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    flex: 1,
  },
  bankAccountIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  bankAccountBank: {
    fontSize: FONTS.sm,
    fontWeight: "700",
    color: COLORS.gray800,
  },
  bankAccountIban: {
    fontSize: FONTS.sm,
    color: COLORS.gray500,
    marginTop: 2,
  },
  bankAccountRight: {
    alignItems: "flex-end",
  },
  bankAccountStatus: {
    fontSize: FONTS.xs,
    fontWeight: "600",
  },
  bankAccountCurrency: {
    fontSize: FONTS.xs,
    color: COLORS.gray400,
    marginTop: 2,
    textTransform: "uppercase",
  },
  pagoPendienteBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.warningSoft || "rgba(245, 158, 11, 0.1)",
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    marginTop: SPACING.sm,
  },
  pagoPendienteInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
  },
  pagoPendienteText: {
    fontSize: FONTS.sm,
    fontWeight: "600",
    color: COLORS.warning,
  },
  retornarPagoBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    backgroundColor: COLORS.warning,
    borderRadius: RADIUS.sm,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs,
  },
  retornarPagoBtnText: {
    fontSize: FONTS.xs,
    fontWeight: "bold",
    color: COLORS.white,
  },
  verPasajerosBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    marginTop: SPACING.xs,
  },
  verPasajerosText: {
    flex: 1,
    fontSize: FONTS.sm,
    fontWeight: "600",
    color: COLORS.primary,
  },
  pasajerosExpandible: {
    backgroundColor: COLORS.gray50 || "#f9fafb",
    borderRadius: RADIUS.md,
    padding: SPACING.sm,
    marginTop: SPACING.xs,
  },
  pasajerosLoading: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingVertical: SPACING.md,
    justifyContent: "center",
  },
  pasajerosLoadingText: {
    fontSize: FONTS.sm,
    color: COLORS.gray500,
  },
  pasajeroRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingVertical: SPACING.xs,
  },
  pasajeroAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.primarySoft || "rgba(0,0,0,0.05)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  pasajeroAvatarImg: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  pasajeroAvatarText: {
    fontSize: FONTS.md,
    fontWeight: "bold",
    color: COLORS.primary,
  },
  pasajeroInfo: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  pasajeroNombre: {
    fontSize: FONTS.sm,
    fontWeight: "600",
    color: COLORS.gray800,
  },
  pasajeroStatusBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 2,
    borderRadius: RADIUS.sm,
  },
  pasajeroStatusCompleted: {
    backgroundColor: COLORS.successSoft || "rgba(34,197,94,0.1)",
  },
  pasajeroStatusPending: {
    backgroundColor: COLORS.warningSoft || "rgba(245,158,11,0.1)",
  },
  pasajeroStatusOther: {
    backgroundColor: COLORS.gray100 || "#f3f4f6",
  },
  pasajeroStatusText: {
    fontSize: FONTS.xs,
    fontWeight: "600",
  },
  pasajerosEmpty: {
    fontSize: FONTS.sm,
    color: COLORS.gray400,
    textAlign: "center",
    paddingVertical: SPACING.md,
  },
});

export default styles;
