// Catálogo local de Marcas y Modelos de Vehículos populares
export const POPULAR_CARS = {
  Toyota: [
    "Corolla",
    "Yaris",
    "RAV4",
    "C-HR",
    "Auris",
    "Prius",
    "Land Cruiser",
    "Hilux",
    "Aygo X",
    "Yaris Cross",
    "Corolla Cross",
    "bZ4X",
    "Camry",
    "Highlander",
    "Proace",
    "Urban Cruiser",
  ],
  Seat: [
    "Ibiza",
    "Leon",
    "Arona",
    "Ateca",
    "Tarraco",
    "Altea",
    "Toledo",
    "Mii",
    "Leon Sportstourer",
    "Ateca FR",
    "Born",
  ],
  Cupra: [
    "Formentor",
    "Leon",
    "Ateca",
    "Born",
    "UrbanRebel",
    "Tavascan",
    "Raval",
  ],
  Renault: [
    "Clio",
    "Megane",
    "Captur",
    "Kadjar",
    "Scenic",
    "Zoe",
    "Laguna",
    "Twingo",
    "Arkana",
    "Austral",
    "Espace",
    "Kangoo",
    "Trafic",
    "Master",
    "Megane E-Tech",
    "Scenic E-Tech",
    "Twingo E-Tech",
    "Rafale",
    "Symbioz",
  ],
  Volkswagen: [
    "Golf",
    "Polo",
    "T-Roc",
    "Tiguan",
    "Passat",
    "Touran",
    "ID.3",
    "ID.4",
    "Caddy",
    "Arteon",
    "T-Cross",
    "Taigo",
    "Touareg",
    "ID.5",
    "ID.7",
    "ID. Buzz",
    "Golf SV",
    "Sharan",
    "Multivan",
  ],
  Peugeot: [
    "208",
    "308",
    "2008",
    "3008",
    "5008",
    "508",
    "Partner",
    "Rifter",
    "108",
    "Expert",
    "Boxer",
    "e-208",
    "e-308",
    "e-2008",
    "e-3008",
    "e-5008",
    "408",
    "Traveller",
  ],
  Ford: [
    "Fiesta",
    "Focus",
    "Kuga",
    "Puma",
    "Mondeo",
    "Mustang",
    "C-Max",
    "Transit",
    "EcoSport",
    "Edge",
    "Galaxy",
    "S-Max",
    "Tourneo",
    "Ranger",
    "Explorer",
    "Mustang Mach-E",
    "Puma Gen-E",
    "Capri",
    "Kuga Gen-E",
  ],
  Opel: [
    "Corsa",
    "Astra",
    "Mokka",
    "Grandland",
    "Insignia",
    "Zafira",
    "Crossland",
    "Combo",
    "Vivaro",
    "Movano",
    "Astra Sports Tourer",
    "Mokka-e",
    "Corsa-e",
    "Frontera",
    "Astra-e",
  ],
  Citroën: [
    "C3",
    "C4",
    "C3 Aircross",
    "C5 Aircross",
    "Berlingo",
    "Saxo",
    "Xsara",
    "C1",
    "C2",
    "C4 Cactus",
    "C4 Picasso",
    "Grand C4 Picasso",
    "Jumper",
    "Jumpy",
    "SpaceTourer",
    "e-C4",
    "e-C3",
    "e-Berlingo",
    "C5 X",
    "Hypnos",
  ],
  BMW: [
    "Serie 1",
    "Serie 2",
    "Serie 3",
    "Serie 4",
    "Serie 5",
    "Serie 7",
    "Serie 8",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "i3",
    "i4",
    "i5",
    "i7",
    "iX",
    "iX1",
    "iX2",
    "iX3",
    "XM",
    "M2",
    "M3",
    "M4",
    "M5",
    "X5 M",
    "X6 M",
    "Z4",
    "Serie 2 Active Tourer",
  ],
  Audi: [
    "A1",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "Q2",
    "Q3",
    "Q4 e-tron",
    "Q5",
    "Q7",
    "Q8",
    "e-tron GT",
    "Q8 e-tron",
    "TT",
    "R8",
    "A3 Sportback",
    "A4 Avant",
    "A6 Avant",
    "Q3 Sportback",
    "Q5 Sportback",
    "RS3",
    "RS6",
    "RSQ8",
    "S3",
    "S4",
    "S5",
    "SQ5",
  ],
  Mercedes: [
    "Clase A",
    "Clase B",
    "Clase C",
    "Clase E",
    "Clase S",
    "Clase CLA",
    "Clase CLS",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLS",
    "G-Class",
    "EQA",
    "EQB",
    "EQC",
    "EQE",
    "EQS",
    "EQV",
    "EQG",
    "Vito",
    "Viano",
    "V-Class",
    "Sprinter",
    "X-Class",
    "AMG GT",
    "AMG A35",
    "AMG C43",
    "AMG E63",
    "Clase C Coupe",
    "Clase E Coupe",
    "SL",
    "SLC",
  ],
  Hyundai: [
    "i10",
    "i20",
    "i30",
    "Tucson",
    "Kona",
    "IONIQ",
    "Santa Fe",
    "Getz",
    "Bayon",
    "Coupé",
    "Accent",
    "Elantra",
    "Sonata",
    "Palisade",
    "Staria",
    "Nexo",
    "IONIQ 5",
    "IONIQ 6",
    "Kona Electric",
    "i30 N",
    "i20 N",
    "Casper",
    "Staria",
  ],
  Kia: [
    "Rio",
    "Ceed",
    "Sportage",
    "Stonic",
    "Niro",
    "Sorento",
    "Picanto",
    "Ceed GT",
    "ProCeed",
    "XCeed",
    "Soul",
    "EV6",
    "EV9",
    "EV5",
    "Niro EV",
    "Niro PHEV",
    "Seltos",
    "Carens",
    "Carnival",
    "Picanto",
    "EV3",
    "Sorento PHEV",
  ],
  Fiat: [
    "500",
    "Panda",
    "Punto",
    "Tipo",
    "Ducato",
    "500X",
    "500L",
    "Punto EVO",
    "Bravo",
    "Doblo",
    "Fiorino",
    "Talento",
    "Strada",
    "500e",
    "600e",
    "Topolino",
    "Pulse",
    "Fastback",
    "Idea",
    "Stilo",
  ],
  Dacia: [
    "Sandero",
    "Duster",
    "Lodgy",
    "Logan",
    "Jogger",
    "Spring",
    "Sandero Stepway",
    "Duster II",
    "Solenza",
    "Bigster",
  ],
  Tesla: [
    "Model 3",
    "Model Y",
    "Model S",
    "Model X",
    "Cybertruck",
    "Model 3 Highland",
    "Model Y Juniper",
    "Roadster",
  ],
  Nissan: [
    "Micra",
    "Qashqai",
    "Juke",
    "Leaf",
    "X-Trail",
    "Ariya",
    "Townstar",
    "Navara",
    "Pathfinder",
    "Juke Hybrid",
    "Qashqai e-Power",
    "X-Trail e-Power",
    "Note",
    "Sunny",
    "Almera",
  ],
  Mazda: [
    "Mazda2",
    "Mazda3",
    "Mazda6",
    "CX-3",
    "CX-30",
    "CX-5",
    "CX-50",
    "CX-60",
    "CX-70",
    "CX-90",
    "MX-5",
    "MX-30",
    "BT-50",
    "Mazda2 Hybrid",
  ],
  Honda: [
    "Civic",
    "Accord",
    "CR-V",
    "HR-V",
    "Jazz",
    "HR-V e:HEV",
    "Civic e:HEV",
    "CR-V e:HEV",
    "e:Ny1",
    "Honda e",
    "City",
    "Pilot",
    "Odyssey",
    "Stepwgn",
    "ZR-V",
  ],
  Volvo: [
    "XC40",
    "XC60",
    "XC90",
    "S60",
    "S90",
    "V60",
    "V90",
    "C40 Recharge",
    "EX30",
    "EX40",
    "EX60",
    "EX90",
    "V60 Cross Country",
    "V90 Cross Country",
    "XC40 Recharge",
    "XC60 Recharge",
    "XC90 Recharge",
    "S60 Recharge",
  ],
  Skoda: [
    "Fabia",
    "Octavia",
    "Superb",
    "Kamiq",
    "Karoq",
    "Kodiaq",
    "Enyaq",
    "Scala",
    "Citigo",
    "Rapid",
    "Roomster",
    "Yeti",
    "Elroq",
    "Epiq",
  ],
  Mitsubishi: [
    "ASX",
    "Outlander",
    "Eclipse Cross",
    "L200",
    "Space Star",
    "Outlander PHEV",
    "Eclipse Cross PHEV",
    "ASX Hybrid",
    "Colt",
    "i-MiEV",
    "Mirage",
  ],
  Suzuki: [
    "Swift",
    "Vitara",
    "Ignis",
    "Celerio",
    "S-Cross",
    "Baleno",
    "Swift Sport",
    "Jimny",
    "Swace",
    "Solio",
    "SX4",
    "Wagon R",
  ],
  Mini: [
    "Cooper",
    "Cooper S",
    "Cooper SE",
    "Countryman",
    "Countryman SE",
    "Clubman",
    "Convertible",
    "Aceman",
    "John Cooper Works",
  ],
  Porsche: [
    "911",
    "718 Cayman",
    "718 Boxster",
    "Taycan",
    "Macan",
    "Macan Electric",
    "Cayenne",
    "Panamera",
    "918 Spyder",
    "Cayenne Coupe",
  ],
  "Land Rover": [
    "Range Rover",
    "Range Rover Sport",
    "Range Rover Velar",
    "Range Rover Evoque",
    "Discovery",
    "Discovery Sport",
    "Defender",
    "Freelander",
  ],
  Jaguar: ["XE", "XF", "XJ", "F-Pace", "E-Pace", "I-Pace", "F-Type", "XK"],
  "Alfa Romeo": [
    "Giulia",
    "Stelvio",
    "Tonale",
    "Giulietta",
    "MiTo",
    "159",
    "156",
    "Brera",
    "Spider",
  ],
  Lexus: [
    "IS",
    "ES",
    "LS",
    "UX",
    "NX",
    "RX",
    "RX L",
    "GX",
    "LX",
    "LC",
    "RC",
    "CT",
    "LB",
    "TX",
    "RZ",
    "UX 300e",
    "NX 450h+",
  ],
  DS: [
    "DS 3",
    "DS 4",
    "DS 7",
    "DS 9",
    "DS 3 Crossback",
    "DS 4 E-Tense",
    "DS 7 E-Tense",
    "DS 9 E-Tense",
  ],
  MG: [
    "ZS",
    "HS",
    "MG3",
    "Marvel R",
    "MG4",
    "MG5",
    "Cyberster",
    "ZS EV",
    "HS PHEV",
    "MG3 Hybrid",
  ],
  Polestar: [
    "Polestar 2",
    "Polestar 3",
    "Polestar 4",
    "Polestar 5",
    "Polestar 6",
  ],
  BYD: [
    "Atto 3",
    "Dolphin",
    "Seal",
    "Seal U",
    "Tang",
    "Han",
    "Yuan Plus",
    "Dolphin Mini",
    "Seagull",
    "Seal U DM-i",
  ],
  SsangYong: [
    "Tivoli",
    "Korando",
    "Rexton",
    "Musso",
    "XLV",
    "Torres",
    "Korando E100",
  ],
  Subaru: [
    "Impreza",
    "Outback",
    "Forester",
    "XV",
    "Crosstrek",
    "Levorg",
    "WRX",
    "BRZ",
    "Solterra",
    "Ascent",
    "Legacy",
  ],
  Chevrolet: [
    "Spark",
    "Aveo",
    "Cruze",
    "Malibu",
    "Tahoe",
    "Traverse",
    "Trax",
    "Equinox",
    "Camaro",
    "Corvette",
    "Bolt",
    "Bolt EUV",
    "Orlando",
  ],
  Jeep: [
    "Renegade",
    "Compass",
    "Cherokee",
    "Grand Cherokee",
    "Wrangler",
    "Gladiator",
    "Avenger",
    "Commander",
    "Meridian",
    "Cherokee L",
    "Wagoneer",
    "Compass 4xe",
    "Renegade 4xe",
    "Avenger Electric",
  ],
  Lancia: ["Ypsilon", "Delta", "Thema", "Musone", "Ypsilon Electric"],
  Smart: [
    "Fortwo",
    "Forfour",
    "EQ fortwo",
    "EQ forfour",
    "Smart #1",
    "Smart #3",
  ],
  Lotus: ["Emira", "Eletre", "Emeya", "Evija", "Exige", "Elise"],
  McLaren: ["Artura", "750S", "765LT", "GT", "Senna", "Elva", "GMA"],
  Bentley: ["Continental GT", "Flying Spur", "Bentayga", "Mulsanne"],
  RollsRoyce: ["Ghost", "Phantom", "Cullinan", "Spectre", "Wraith", "Dawn"],
  Ferrari: [
    "Roma",
    "296 GTB",
    "296 GTS",
    "SF90 Stradale",
    "SF90 Spider",
    "812 Competizione",
    "Purosangue",
    "12Cilindri",
  ],
  Lamborghini: ["Huracán", "Aventador", "Urus", "Revuelto", "Countach"],
  Maserati: [
    "Ghibli",
    "Levante",
    "Quattroporte",
    "MC20",
    "Grecale",
    "GranTurismo",
    "GranCabrio",
  ],
  AstonMartin: ["Vantage", "DB11", "DB12", "DBX", "Valkyrie", "Valhalla"],
  Rivian: ["R1T", "R1S", "R2", "R3", "R3X"],
  Lucid: ["Air", "Gravity", "Sapphire"],
  Nio: ["ET5", "ET7", "ES6", "ES7", "ES8", "EC6", "EC7"],
  Xpeng: ["G9", "P7", "P5", "G6", "G3"],
  Omoda: ["Omoda 5", "Omoda 7", "Omoda 9"],
  Jaecoo: ["Jaecoo 7"],
  Aito: ["M5", "M7", "M9"],
  Zeekr: ["001", "007", "X", "7X", "009"],
};

export const FUEL_TYPES = [
  { label: "Gasolina", value: "Gasolina" },
  { label: "Diésel", value: "Diesel" },
  { label: "Híbrido", value: "Hibrido" },
  { label: "Eléctrico", value: "Electrico" },
];

export const CAR_COLORS = [
  "Blanco",
  "Negro",
  "Gris Plata",
  "Gris Oscuro",
  "Azul",
  "Rojo",
  "Verde",
  "Amarillo",
  "Naranja",
  "Marrón",
  "Beige",
];
